/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ANSH DESAI
 */
public class AddBook extends javax.swing.JInternalFrame {
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    /**
     * Creates new form AddBook
     */
    public AddBook() {
        initComponents();
        conn= MySqlConnect.ConnectDB();
        autoid();
        tableload();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame2 = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        btnadd1 = new javax.swing.JButton();
        btnupdate1 = new javax.swing.JButton();
        btnremove1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtmid1 = new javax.swing.JTextField();
        txtname1 = new javax.swing.JTextField();
        txtnic1 = new javax.swing.JTextField();
        gender1 = new javax.swing.JComboBox<>();
        txtemail1 = new javax.swing.JTextField();
        txtcontact1 = new javax.swing.JTextField();
        mtype1 = new javax.swing.JComboBox<>();
        datechooser1 = new com.toedter.calendar.JDateChooser();
        t1 = new javax.swing.JScrollPane();
        txtaddress1 = new javax.swing.JTextArea();
        jLabel28 = new javax.swing.JLabel();
        tabledetails1 = new javax.swing.JScrollPane();
        tabledetail1 = new javax.swing.JTable();
        jLabel29 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnbadd = new javax.swing.JButton();
        btnbupdate = new javax.swing.JButton();
        btnbremove = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        txtbid = new javax.swing.JTextField();
        txtbname = new javax.swing.JTextField();
        txtisbn = new javax.swing.JTextField();
        txtcategory = new javax.swing.JComboBox<>();
        txtprice = new javax.swing.JTextField();
        txtauthor = new javax.swing.JTextField();
        txtbdate = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        t2 = new javax.swing.JScrollPane();
        txtpublisher = new javax.swing.JTextArea();
        jLabel42 = new javax.swing.JLabel();
        tabledetails2 = new javax.swing.JScrollPane();
        txtbtable = new javax.swing.JTable();
        jLabel43 = new javax.swing.JLabel();
        txtbtype = new javax.swing.JComboBox<>();

        jInternalFrame2.setBackground(new java.awt.Color(204, 204, 255));
        jInternalFrame2.setClosable(true);
        jInternalFrame2.setPreferredSize(new java.awt.Dimension(950, 650));
        jInternalFrame2.setVisible(false);

        jPanel2.setBackground(new java.awt.Color(236, 226, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnadd1.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        btnadd1.setText("ADD");
        btnadd1.setActionCommand("");
        btnadd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadd1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnadd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 120, 120, 40));

        btnupdate1.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        btnupdate1.setText("UPDATE");
        btnupdate1.setActionCommand("");
        btnupdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdate1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnupdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 190, 120, 40));

        btnremove1.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        btnremove1.setText("REMOVE");
        btnremove1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnremove1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnremove1, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 265, 120, 40));

        jLabel16.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        jLabel16.setText("MyID");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 110, 20));

        jLabel17.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        jLabel17.setText("Name");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 110, 20));

        jLabel18.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        jLabel18.setText("NIC");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 110, 40));

        jLabel19.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        jLabel19.setText("Birthdate");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 120, 60));

        jLabel20.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        jLabel20.setText("Gender");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 110, 20));

        jLabel21.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        jLabel21.setText("Address");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 90, 20));

        jLabel22.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        jLabel22.setText("Email");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 100, 30));

        jLabel23.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        jLabel23.setText("Contact No.");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 100, -1));

        jLabel24.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        jLabel24.setText("Member Type");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 110, 30));

        jLabel25.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1050, -1));

        jLabel26.setBackground(new java.awt.Color(204, 204, 255));
        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 590));

        jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 70));

        txtmid1.setEditable(false);
        jPanel2.add(txtmid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 180, -1));
        jPanel2.add(txtname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 180, -1));
        jPanel2.add(txtnic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 180, -1));

        gender1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "Female" }));
        jPanel2.add(gender1, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 310, 120, -1));
        jPanel2.add(txtemail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 180, -1));
        jPanel2.add(txtcontact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 180, -1));

        mtype1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select type", "Student", "Other" }));
        jPanel2.add(mtype1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 120, -1));
        jPanel2.add(datechooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 130, 30));

        txtaddress1.setColumns(20);
        txtaddress1.setRows(5);
        t1.setViewportView(txtaddress1);

        jPanel2.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 180, 60));

        jLabel28.setToolTipText("");
        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 220, 240));

        tabledetails1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        tabledetail1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabledetail1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabledetail1MouseClicked(evt);
            }
        });
        tabledetails1.setViewportView(tabledetail1);

        jPanel2.add(tabledetails1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 421, 1050, 170));

        jLabel29.setFont(new java.awt.Font("Ink Free", 1, 40)); // NOI18N
        jLabel29.setText("Members Community");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 390, 40));

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setPreferredSize(new java.awt.Dimension(1050, 700));

        jPanel3.setBackground(new java.awt.Color(236, 226, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnbadd.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        btnbadd.setText("ADD");
        btnbadd.setActionCommand("");
        btnbadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbaddActionPerformed(evt);
            }
        });
        jPanel3.add(btnbadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 120, 160, 40));

        btnbupdate.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        btnbupdate.setText("UPDATE");
        btnbupdate.setActionCommand("");
        btnbupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbupdateActionPerformed(evt);
            }
        });
        jPanel3.add(btnbupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 190, 160, 40));

        btnbremove.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        btnbremove.setText("REMOVE");
        btnbremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbremoveActionPerformed(evt);
            }
        });
        jPanel3.add(btnbremove, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 265, 160, 40));

        jLabel30.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        jLabel30.setText("BookID");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 110, 20));

        jLabel31.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        jLabel31.setText("Name");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 110, 20));

        jLabel32.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        jLabel32.setText("ISBN");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 110, 40));

        jLabel33.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        jLabel33.setText("Date");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 120, 60));

        jLabel34.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        jLabel34.setText("Category");
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 110, 20));

        jLabel35.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        jLabel35.setText("Publisher");
        jPanel3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 90, 20));

        jLabel36.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        jLabel36.setText("Price");
        jPanel3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 100, 30));

        jLabel37.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        jLabel37.setText("Author");
        jPanel3.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 100, 30));

        jLabel39.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        jLabel39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1050, -1));

        jLabel40.setBackground(new java.awt.Color(204, 204, 255));
        jLabel40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 590));

        jLabel41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 70));

        txtbid.setEditable(false);
        jPanel3.add(txtbid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 180, -1));
        jPanel3.add(txtbname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 180, -1));
        jPanel3.add(txtisbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 180, -1));

        txtcategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Category", "History", "Philosohpy", "Science", "Fiction", "Biography" }));
        jPanel3.add(txtcategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 310, 120, -1));
        jPanel3.add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 212, 180, 30));
        jPanel3.add(txtauthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 252, 180, 30));
        jPanel3.add(txtbdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 130, 30));

        jLabel1.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        jLabel1.setText("Type");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 350, 60, -1));

        txtpublisher.setColumns(20);
        txtpublisher.setRows(5);
        t2.setViewportView(txtpublisher);

        jPanel3.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 180, 70));

        jLabel42.setToolTipText("");
        jLabel42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 260, 240));

        tabledetails2.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtbtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        txtbtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtbtableMouseClicked(evt);
            }
        });
        tabledetails2.setViewportView(txtbtable);

        jPanel3.add(tabledetails2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 421, 970, 170));

        jLabel43.setFont(new java.awt.Font("Ink Free", 1, 40)); // NOI18N
        jLabel43.setText("Booksforall ");
        jPanel3.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 390, 40));

        txtbtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select type", "Borrow", "Read-only" }));
        txtbtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbtypeActionPerformed(evt);
            }
        });
        jPanel3.add(txtbtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 350, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1013, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 989, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnadd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadd1ActionPerformed

    }//GEN-LAST:event_btnadd1ActionPerformed

    private void btnupdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdate1ActionPerformed
      
    }//GEN-LAST:event_btnupdate1ActionPerformed

    private void btnremove1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnremove1ActionPerformed
       
    }//GEN-LAST:event_btnremove1ActionPerformed

    private void tabledetail1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabledetail1MouseClicked
        
    }//GEN-LAST:event_tabledetail1MouseClicked

    private void txtbtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbtableMouseClicked
        DefaultTableModel tmodel = (DefaultTableModel)txtbtable.getModel();
        int selectrowindex = txtbtable.getSelectedRow();
        txtbid.setText(tmodel.getValueAt(selectrowindex,0).toString());
        txtbname.setText(tmodel.getValueAt(selectrowindex,1).toString());
        txtisbn.setText(tmodel.getValueAt(selectrowindex,2).toString());
        ((JTextField)txtbdate.getDateEditor().getUiComponent()).setText(tmodel.getValueAt(selectrowindex,3).toString());
        txtcategory.setSelectedItem(tmodel.getValueAt(selectrowindex,4).toString());
        txtprice.setText(tmodel.getValueAt(selectrowindex,6).toString());
        txtauthor.setText(tmodel.getValueAt(selectrowindex,7).toString());
        txtpublisher.setText(tmodel.getValueAt(selectrowindex,5).toString());
        txtbtype.setSelectedItem(tmodel.getValueAt(selectrowindex,8).toString());
        
    }//GEN-LAST:event_txtbtableMouseClicked

    private void btnbremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbremoveActionPerformed
try {
              String sql="DELETE FROM `addbook` WHERE bid='"+txtbid.getText()+"'";
      
            PreparedStatement pat = (PreparedStatement) conn.prepareStatement(sql);
            pat.execute();
            JOptionPane.showMessageDialog(rootPane,"Successfully removed");
            tableload();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane,e);
        }
    }//GEN-LAST:event_btnbremoveActionPerformed

    private void btnbupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbupdateActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        String path = filename;
        String newpath = path.replace('\\', '/');
        File pdfFile = new File(newpath);
        FileInputStream input = null;
        String bid = txtbid.getText();
        String bname = txtbname.getText();
        String isbn = txtisbn.getText();
        String date = ((JTextField)txtbdate.getDateEditor().getUiComponent()).getText();
        String category = txtcategory.getSelectedItem().toString();
        String btype = txtbtype.getSelectedItem().toString();
        String publisher = txtpublisher.getText();
        String price = txtprice.getText();
        String author = txtauthor.getText();
        
        try {
        input = new FileInputStream(pdfFile);
    } catch (FileNotFoundException ex) {
        JOptionPane.showMessageDialog(rootPane,ex);
    }
        
        try {
              String sql="UPDATE `addbook` SET `name`='"+bname+"',`isbn`='"+isbn+"',`date`='"+date+"',`category`='"+category+"',`publisher`='"+publisher+"',`price`='"+price+"',`author`='"+author+"',`type`='"+btype+"',`book`=? WHERE bid='"+bid+"'";
      
            PreparedStatement pat = (PreparedStatement) conn.prepareStatement(sql);
             pat.setBinaryStream(1, input, 1000000);  // byte[] array
            pat.executeUpdate();
            JOptionPane.showMessageDialog(rootPane,"Successfully updated");
            tableload();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane,e);
        }
         clearfields();
    }//GEN-LAST:event_btnbupdateActionPerformed

    private void btnbaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbaddActionPerformed
        
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        String path = filename;
        String newpath = path.replace('\\', '/');
        File pdfFile = new File(newpath);
        FileInputStream input = null;
    
        String bid = txtbid.getText();
        String bname = txtbname.getText();
        String isbn = txtisbn.getText();
        String date = ((JTextField)txtbdate.getDateEditor().getUiComponent()).getText();
        String category = txtcategory.getSelectedItem().toString();
        String btype = txtbtype.getSelectedItem().toString();
        String publisher = txtpublisher.getText();
        String price = txtprice.getText();
        String author = txtauthor.getText();
        
          try {
             
    try {
        input = new FileInputStream(pdfFile);
    } catch (FileNotFoundException ex) {
        JOptionPane.showMessageDialog(rootPane,ex);
    }
              String sql="INSERT INTO `addbook`(`bid`, `name`, `isbn`, `date`, `category`, `publisher`, `price`, `author`, `type`, `book`) VALUES ('"+bid+"','"+bname+"','"+isbn+"','"+date+"','"+category+"','"+publisher+"','"+price+"','"+author+"','"+btype+"',?)";
      
            PreparedStatement pat = (PreparedStatement) conn.prepareStatement(sql);
            
            
            pat.setBinaryStream(1, input, 1000000);  // byte[] array
            pat.executeUpdate();
            JOptionPane.showMessageDialog(rootPane,"Successfully added");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane,e);
        }
          clearfields();
        autoid();
        tableload();
    }//GEN-LAST:event_btnbaddActionPerformed

    private void txtbtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbtypeActionPerformed
private void autoid(){
        try{
            String sql = "SELECT `bid` FROM `addbook` ORDER BY bid DESC LIMIT 100";
            pst = (PreparedStatement) conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if(rs.next()){
                String rnno = rs.getString("bid");
                int co = rnno.length();
                String txt = rnno.substring(0,2);
                String num = rnno.substring(2,co);
                int n = Integer.parseInt(num);
                n++;
                String snum = Integer.toString(n);
                String ftxt = txt+snum;
                txtbid.setText(ftxt);
                
            }
            else{
                txtbid.setText("BN1000");
            }
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane,e);
        }
    }
private void tableload(){
         String sql = "SELECT `bid`, `name`, `isbn`, `date`, `category`, `publisher`, `price`, `author`, `type` FROM `addbook`txtbtable";
        try {
            pst = (PreparedStatement) conn.prepareStatement(sql);
            rs = pst.executeQuery();
            txtbtable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception ex) {
            JOptionPane.showConfirmDialog(rootPane,ex);
        }
            
    }
private void clearfields(){
    txtbid.setText("");
        txtbname.setText("");
        txtprice.setText("");
        ((JTextField)txtbdate.getDateEditor().getUiComponent()).setText("");
        txtcategory.setSelectedIndex(0);
        txtbtype.setSelectedIndex(0);
        txtauthor.setText("");
        txtpublisher.setText("");
        
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd1;
    private javax.swing.JButton btnbadd;
    private javax.swing.JButton btnbremove;
    private javax.swing.JButton btnbupdate;
    private javax.swing.JButton btnremove1;
    private javax.swing.JButton btnupdate1;
    private com.toedter.calendar.JDateChooser datechooser1;
    private javax.swing.JComboBox<String> gender1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> mtype1;
    private javax.swing.JScrollPane t1;
    private javax.swing.JScrollPane t2;
    private javax.swing.JTable tabledetail1;
    private javax.swing.JScrollPane tabledetails1;
    private javax.swing.JScrollPane tabledetails2;
    private javax.swing.JTextArea txtaddress1;
    private javax.swing.JTextField txtauthor;
    private com.toedter.calendar.JDateChooser txtbdate;
    private javax.swing.JTextField txtbid;
    private javax.swing.JTextField txtbname;
    private javax.swing.JTable txtbtable;
    private javax.swing.JComboBox<String> txtbtype;
    private javax.swing.JComboBox<String> txtcategory;
    private javax.swing.JTextField txtcontact1;
    private javax.swing.JTextField txtemail1;
    private javax.swing.JTextField txtisbn;
    private javax.swing.JTextField txtmid1;
    private javax.swing.JTextField txtname1;
    private javax.swing.JTextField txtnic1;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextArea txtpublisher;
    // End of variables declaration//GEN-END:variables
}
