/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author ANSH DESAI
 */
public class AddMember extends javax.swing.JInternalFrame {
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    
public AddMember() {
        initComponents();
        conn= MySqlConnect.ConnectDB();
        autoid();
        tableload();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnadd = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnremove = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtmid = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtnic = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox<>();
        txtemail = new javax.swing.JTextField();
        txtcontact = new javax.swing.JTextField();
        mtype = new javax.swing.JComboBox<>();
        datechooser = new com.toedter.calendar.JDateChooser();
        t = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        tabledetails = new javax.swing.JScrollPane();
        tabledetail = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setClosable(true);
        setPreferredSize(new java.awt.Dimension(950, 650));
        setVisible(false);

        jPanel1.setBackground(new java.awt.Color(236, 226, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnadd.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        btnadd.setText("ADD");
        btnadd.setActionCommand("");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        jPanel1.add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 120, 120, 40));

        btnupdate.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        btnupdate.setText("UPDATE");
        btnupdate.setActionCommand("");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 190, 120, 40));

        btnremove.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        btnremove.setText("REMOVE");
        btnremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnremoveActionPerformed(evt);
            }
        });
        jPanel1.add(btnremove, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 265, 120, 40));

        jLabel4.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        jLabel4.setText("MyID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 110, 20));

        jLabel5.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        jLabel5.setText("Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 110, 20));

        jLabel6.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        jLabel6.setText("NIC");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 110, 40));

        jLabel7.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        jLabel7.setText("Birthdate");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 120, 60));

        jLabel8.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        jLabel8.setText("Gender");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 110, 20));

        jLabel9.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        jLabel9.setText("Address");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 90, 20));

        jLabel10.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        jLabel10.setText("Email");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 100, 30));

        jLabel11.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        jLabel11.setText("Contact No.");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 100, -1));

        jLabel12.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        jLabel12.setText("Member Type");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 110, 30));

        jLabel3.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1050, -1));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 590));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 70));

        txtmid.setEditable(false);
        jPanel1.add(txtmid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 180, -1));
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 180, -1));
        jPanel1.add(txtnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 180, -1));

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "Female" }));
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 310, 120, -1));
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 180, -1));
        jPanel1.add(txtcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 180, -1));

        mtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select type", "Student", "Other" }));
        jPanel1.add(mtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 120, -1));
        jPanel1.add(datechooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 130, 30));

        txtaddress.setColumns(20);
        txtaddress.setRows(5);
        t.setViewportView(txtaddress);

        jPanel1.add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 180, 60));

        jLabel13.setToolTipText("");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 220, 240));

        tabledetails.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        tabledetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabledetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabledetailMouseClicked(evt);
            }
        });
        tabledetails.setViewportView(tabledetail);

        jPanel1.add(tabledetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 421, 1050, 170));

        jLabel14.setFont(new java.awt.Font("Ink Free", 1, 40)); // NOI18N
        jLabel14.setText("Members Community");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 390, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        
        String mid = txtmid.getText();
        String name = txtname.getText();
        String nic = txtnic.getText();
        String date = ((JTextField)datechooser.getDateEditor().getUiComponent()).getText();
        String gend = gender.getSelectedItem().toString();
        String address = txtaddress.getText();
        String email = txtemail.getText();
        String contact = txtcontact.getText();
        String type = mtype.getSelectedItem().toString();
        
          try {
              String sql="INSERT INTO `addmember`(`mid`, `mname`, `nic`, `birthday`, `gender`, `address`, `email`, `contact`, `type`) VALUES ('"+mid+"','"+name+"','"+nic+"','"+date+"','"+gend+"','"+address+"','"+email+"','"+contact+"','"+type+"')";
      
            PreparedStatement pat = (PreparedStatement) conn.prepareStatement(sql);
            pat.execute();
            JOptionPane.showMessageDialog(rootPane,"Successfully added");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane,e);
        }
          clearfields();
        autoid();
        tableload();
        
    }//GEN-LAST:event_btnaddActionPerformed

    private void tabledetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabledetailMouseClicked
        DefaultTableModel tmodel = (DefaultTableModel)tabledetail.getModel();
        int selectrowindex = tabledetail.getSelectedRow();
        txtmid.setText(tmodel.getValueAt(selectrowindex,0).toString());
        txtname.setText(tmodel.getValueAt(selectrowindex,1).toString());
        txtnic.setText(tmodel.getValueAt(selectrowindex,2).toString());
        ((JTextField)datechooser.getDateEditor().getUiComponent()).setText(tmodel.getValueAt(selectrowindex,3).toString());
        gender.setSelectedItem(tmodel.getValueAt(selectrowindex,4).toString());
        txtaddress.setText(tmodel.getValueAt(selectrowindex,5).toString());
        txtcontact.setText(tmodel.getValueAt(selectrowindex,7).toString());
        txtemail.setText(tmodel.getValueAt(selectrowindex,6).toString());
        mtype.setSelectedItem(tmodel.getValueAt(selectrowindex,8).toString());
        
    }//GEN-LAST:event_tabledetailMouseClicked

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        String mid = txtmid.getText();
        String name = txtname.getText();
        String nic = txtnic.getText();
        String date = ((JTextField)datechooser.getDateEditor().getUiComponent()).getText();
        String gend = gender.getSelectedItem().toString();
        String address = txtaddress.getText();
        String email = txtemail.getText();
        String contact = txtcontact.getText();
        String type = mtype.getSelectedItem().toString();
        
        try {
              String sql="UPDATE `addmember` SET `mname`='"+name+"',`nic`='"+nic+"',`birthday`='"+date+"',`gender`='"+gend+"',`address`='"+address+"',`email`='"+email+"',`contact`='"+contact+"',`type`='"+type+"' WHERE mid='"+mid+"'";
      
            PreparedStatement pat = (PreparedStatement) conn.prepareStatement(sql);
            pat.execute();
            JOptionPane.showMessageDialog(rootPane,"Successfully updated");
            tableload();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane,e);
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnremoveActionPerformed
        try {
              String sql="DELETE FROM `addmember` WHERE mid='"+txtmid.getText()+"'";
      
            PreparedStatement pat = (PreparedStatement) conn.prepareStatement(sql);
            pat.execute();
            JOptionPane.showMessageDialog(rootPane,"Successfully removed");
            tableload();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane,e);
        }
    }//GEN-LAST:event_btnremoveActionPerformed

    private void autoid(){
        try{
            String sql = "SELECT `mid` FROM `addmember` ORDER BY mid DESC LIMIT 100";
            pst = (PreparedStatement) conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if(rs.next()){
                String rnno = rs.getString("mid");
                int co = rnno.length();
                String txt = rnno.substring(0,2);
                String num = rnno.substring(2,co);
                int n = Integer.parseInt(num);
                n++;
                String snum = Integer.toString(n);
                String ftxt = txt+snum;
                txtmid.setText(ftxt);
                
            }
            else{
                txtmid.setText("MT1000");
            }
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane,e);
        }
    }
    private void tableload(){
         String sql = "SELECT `mid`, `mname`, `nic`, `birthday`, `gender`, `address`, `email`, `contact`, `type` FROM `addmember`tabledetails";
        try {
            pst = (PreparedStatement) conn.prepareStatement(sql);
            rs = pst.executeQuery();
            tabledetail.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception ex) {
            JOptionPane.showConfirmDialog(rootPane,ex);
        }
            
    }
    
private void clearfields(){
    txtmid.setText("");
        txtname.setText("");
        txtnic.setText("");
        ((JTextField)datechooser.getDateEditor().getUiComponent()).setText("");
        gender.setSelectedIndex(0);
        txtaddress.setText("");
        txtemail.setText("");
        txtcontact.setText("");
        mtype.setSelectedIndex(0);
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnremove;
    private javax.swing.JButton btnupdate;
    private com.toedter.calendar.JDateChooser datechooser;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> mtype;
    private javax.swing.JScrollPane t;
    private javax.swing.JTable tabledetail;
    private javax.swing.JScrollPane tabledetails;
    private javax.swing.JTextArea txtaddress;
    private javax.swing.JTextField txtcontact;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtmid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnic;
    // End of variables declaration//GEN-END:variables
}
